spring:
  application:
    name: Blockchain

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

arkham:
  provider: customProvider
  apiKey: "YOUR_API_KEY"  # Если требуется ключ доступа
  baseUrl: "https://intel.arkm.com/explorer/address/"

logging:
  level:
    root: INFO                 # Общий уровень логирования
    com.blockchain: DEBUG      # Логирование для вашего пакета
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/blockchain.log  # Логи пишутся в этот файл
